spring:
  kafka:
    bootstrap-servers: broker:9093

  datasource:
    url: jdbc:postgresql://reddit-db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver